<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="38" started-at="2016-06-06T12:32:51Z" finished-at="2016-06-06T12:32:51Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="38" started-at="2016-06-06T12:32:51Z" finished-at="2016-06-06T12:32:51Z">
      <class name="StackTest">
        <test-method status="PASS" signature="stackFirstElement()[pri:0, instance:StackTest@419c5f1a]" name="stackFirstElement" duration-ms="0" started-at="2016-06-06T14:32:51Z" finished-at="2016-06-06T14:32:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stackFirstElement -->
        <test-method status="PASS" signature="stackFirstElement_Pop_checkSize()[pri:0, instance:StackTest@419c5f1a]" name="stackFirstElement_Pop_checkSize" duration-ms="0" started-at="2016-06-06T14:32:51Z" finished-at="2016-06-06T14:32:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stackFirstElement_Pop_checkSize -->
        <test-method status="PASS" signature="stackFirstElement_Pop_element()[pri:0, instance:StackTest@419c5f1a]" name="stackFirstElement_Pop_element" duration-ms="0" started-at="2016-06-06T14:32:51Z" finished-at="2016-06-06T14:32:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stackFirstElement_Pop_element -->
        <test-method status="PASS" signature="stackFirstElement_Pop_elementMultiple()[pri:0, instance:StackTest@419c5f1a]" name="stackFirstElement_Pop_elementMultiple" duration-ms="0" started-at="2016-06-06T14:32:51Z" finished-at="2016-06-06T14:32:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stackFirstElement_Pop_elementMultiple -->
        <test-method status="FAIL" signature="stackFirstElement_Pop_failure()[pri:0, instance:StackTest@419c5f1a]" name="stackFirstElement_Pop_failure" duration-ms="0" started-at="2016-06-06T14:32:51Z" finished-at="2016-06-06T14:32:51Z">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Method StackTest.stackFirstElement_Pop_failure()[pri:0, instance:StackTest@419c5f1a] should have thrown an exception of type class javax.activity.InvalidActivityException]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Method StackTest.stackFirstElement_Pop_failure()[pri:0, instance:StackTest@419c5f1a] should have thrown an exception of type class javax.activity.InvalidActivityException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1350)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:684)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stackFirstElement_Pop_failure -->
      </class> <!-- StackTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
